name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag arnolin/ubuntu:latest
    
    - name: save
      uses: actions/upload-artifact@v2
      with: 
        name: docker-image
        path: /arnolin/ubuntu
